# Anmerkung: Die Bilder sind bereits in Graustufen, da die letzte Dimension
in der data.npy 1 ist. Waere diese Dimension 3 gewesen, dann handelt es sich
um ein rgb-Bild.
Zum Vergleich der Groesse dieser Dimension zw. einem rgb- und graustufigen
Bild siehe /Users/affandimansor/Weiterbildung_velpTEC/TensorFlow/Kapitel_2/uebung_2_u_03.py
# Skalieren die Pixelwerte um maximalen Wert, um das Problem mit verschwindenden Gradienten
zu vermeiden.

@startuml
title Workflow Data Preparation

:Das Merkmal bzw. die Pixel und
Labels aus jeweiliger .npy-Datei
in den Workspace einlesen;
:Die Pixelwerte werden durch
z-Score standardziert;
:Die zwei Datenmenge in zu einem
Datensatz zusammenführen;
:Den Datensatz in Trainings- und
Testdatenmenge aufteilen;
:Die Trainingsdatenmenge in zwei weitere
Datenmengen nämlich Training und 
Validierungsdatenmenge auteilen;
:MiniBatches der Trainings- und
Validierungsdatenmenge erstellen;
@enduml